### ISSUE TITLE
status of project

### ISSUE THREAD

**Issue by c-cube** [fxfactorial/ocaml-linenoise#1]
It seems that the repo hasn't moved much recently. I'd be interested in helping maintening the code and moving it forward (e.g. adding some direly missing escape keys such as ctrl-l or ctrl-{left,right}).

**Comment by fxfactorial** [comment]
Sure, go for it! Do you want direct commit access?

**Comment by c-cube** [comment]
Sure, would be great! :+1:

**Comment by fxfactorial** [comment]
added

**Comment by c-cube** [comment]
Thank you! Do you want me to keep you informed of the changes I make, or would you rather no be bothered with the project anymore?

**Comment by fxfactorial** [comment]
You do with it as you please, I’ll watch from distance and will never override you.
