### ISSUE TITLE
lintian info on Debian package

### ISSUE THREAD

**Issue by yuzibo** [fxfactorial/ocaml-linenoise#22]
Hi,

I am packaging this package to Debian. But now I get one lintian info as follows:

```
I: liblinenoise-ocaml-dev: unstripped-static-library (lNoise.o) [usr/lib/ocaml/linenoise/linenoise.a]
```
This is not a real issue from my review. But on Debian, there is one tool called debhelper([dh_strip](https://github.com/Debian/debhelper/blob/master/dh_strip#L239C2-L244C27)) to strip these static libraries like `libstatic-library.a` name scheme:

```
# Is it a static library, and not a debug library?
	if ($fn =~ m/\/lib[^\/]*\.a$/ && $fn !~ m/.*_g\.a$/) {
		# Is it a binary file, or something else (maybe a linker
		# script on Hurd, for example? I don't use file, because
		# file returns a variety of things on static libraries.
		if (-B $fn) {
			push @static_libs, $fn;
			return;
		}
	}
```

I can use lintian-override to override the info on the package. But before do this, I should forward this upstream and could  I ask if we can convert linenoise.a to liblinenoise.a?

TIA.

**Comment by c-cube** [comment]
Sorry, I forgot about this. Changing `linenoise.a` to `liblinenoise.a` seems fine to me, I think — it wouldn't be visible from the outside anyway?

**Comment by yuzibo** [comment]
hmm, maybe we do not need to change this in the OCaml context.

More detailed explanation see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1068651#29)

So I close the issue if needed please reopen it.
