### ISSUE TITLE
support ctrl-{left,right}

### ISSUE THREAD

**Issue by c-cube** [fxfactorial/ocaml-linenoise#5]
- at least do not output ugly escape codes
- at best, move to prev/next word boundary

**Comment by fxfactorial** [comment]
Don’t you think these changes would be better in upstream line noise ?

**Comment by c-cube** [comment]
I agree, but upstream seems really, really dead. Even the patch for multi-line paste (2db5019c0abc5c5d8a2068609b20953ffddc31b8) seems dead there: https://github.com/antirez/linenoise/issues/43
